// <auto-generated />
using System;
using API_PetShop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PetShop.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20250815060701_PetShop")]
    partial class PetShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_PetShop.Entidades.Cachorro", b =>
                {
                    b.Property<int>("CachorroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CachorroId"));

                    b.Property<DateTime>("DataDoBanho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("Porte")
                        .HasColumnType("int");

                    b.Property<string>("Raca")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorBanho")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("CachorroId");

                    b.ToTable("Cachorros");
                });
#pragma warning restore 612, 618
        }
    }
}
